#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define MIN_PWD_LEN  8
#define MAX_PWD_LEN  64
#define MAX_SERVICE_N_USER_LEN  128
#define MASTER_HASH_LEN  MAX_PWD_LEN
#define VAULT_MAX 100

#define VAULT_FILE_EXT ".gcm"

#define RET_SUCCESS 0
#define ERR_VAULT_ALREADY_EXISTS 1
#define ERR_INVALID_MASTER_PASSWORD 2
#define ERR_VAULT_FULL 3
#define ERR_CANNOT_SEAL_VAULT 4
#define ERR_CANNOT_SAVE_TO_FILE 5
#define ERR_CANNOT_LOAD_FROM_FILE 6
#define ERR_CANNOT_UNSEAL_VAULT 7
#define ERR_SERVICE_USERNAME_NOT_FOUND 8




#endif